version: '3'

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: todo_app:prod
    ports:
      - "5800:8000"
    env_file:
      - ".env"
    profiles:
      - prod
    network_mode: "bridge"

  development:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    image: todo_app:dev
    ports:
      - "5800:5000"
    env_file:
      - ".env"
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
    profiles:
      - dev
    network_mode: "bridge"
  
  testing:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    image: todo_app:test
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
    profiles:
      - test
    network_mode: "bridge"
