version: '3'

services:
  base:
    build: 
      context: .
      dockerfile: Dockerfile
      target: full_install
    image: todo-app:base
    profiles:
      - base

  production:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: todo-app:prod
    ports:
      - "5800:8000"
    network_mode: "bridge"
    env_file:
      - ".env"
    profiles:
      - prod
 
  release:
    extends: production
    build:
      target: release
    image: todo-app
    profiles:
      - release

  development:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    image: todo-app:dev
    ports:
      - "5800:5000"
    network_mode: "bridge"
    env_file:
      - ".env"
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
    profiles:
      - dev

  testing:
    build: 
      context: .
      dockerfile: Dockerfile
      target: testing
    image: todo-app:test
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
    profiles:
      - test

  e2e_testing:
    build: 
      context: .
      dockerfile: Dockerfile
      target: e2e_testing
    image: todo-app:e2e_test
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
    env_file:
      - ".env"
    profiles:
      - e2e_test
    network_mode: "bridge"

  linter:
    build: 
      context: .
      dockerfile: Dockerfile
      target: full_install
    command: "poetry run autopep8 -r -i --max-line-length=200 --ignore-local-config ."
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
      - type: bind
        source: ./tests
        target: /app/tests
      - type: bind
        source: ./e2e_tests
        target: /app/e2e_tests
    image: todo_app:full_install
    profiles:
      - lint

  check_style:
    extends: linter
    command: "poetry run pycodestyle --max-line-length=200 todo_app tests e2e_tests"
    image: todo_app:full_install
    profiles:
      - check-style