name: End 2 End tests
on:
  pull_request:
      branches:
          - main

jobs:
    build:
        name: E2E tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build test image
              run: docker compose build e2e_testing

            - name: Run e2e tests
              run: docker compose run e2e_testing