name: CI
on: [push]

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Setup .env
              run: cp .env.template .env

            - name: Build Production
              run: docker compose build production

            - name: Build Tests
              run: docker compose build testing

            - name: Run tests
              run: docker compose up testing