name: Test
on: [push]

jobs:
    build:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build Tests
              run: docker compose build testing

            - name: Run tests
              run: docker compose up testing